### ISSUE TITLE
Path to plugin in readme is wrong?

### ISSUE THREAD

**Issue by sparsematrix** [cordova-ccafix/cordova-plugin-client-certificate-support#11]
The readme uses this as the example to install the plugin, which points to the mywaylabs plugin:
cordova plugin add https://github.com/mwaylabs/cordova-plugin-client-certificate

Should it not be this?
cordova plugin add https://github.com/cordova-ccafix/cordova-plugin-client-certificate-support

**Comment by brody2consult** [comment]
Yes, thanks!
